import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./_Compenents/_header/NavBar";
import Footer from "./_Compenents/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "MyStore",
  description: "Generated by create next app",
  
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="bg-[#FAFAFA]">
          <NavBar />
          {children}

          <Footer />
        </main>
      </body>
    </html>
  );
}
